apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-gs
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: k8s-gs-api
          image: k8s-gs:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "20" ]
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-gs-api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
